repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^eff_word_net/
    -   id: end-of-file-fixer
        exclude: ^eff_word_net/
    -   id: check-yaml
        exclude: ^eff_word_net/
    -   id: debug-statements
        exclude: ^eff_word_net/
    -   id: double-quote-string-fixer
        exclude: ^eff_word_net/
    -   id: name-tests-test
        exclude: ^eff_word_net/
    -   id: requirements-txt-fixer
        exclude: ^eff_word_net/
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.5.0
    hooks:
    -   id: setup-cfg-fmt
        exclude: ^eff_word_net/
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma
        exclude: ^eff_word_net/
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
        exclude: ^eff_word_net/
-   repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
    -   id: autopep8
        exclude: ^eff_word_net/
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        exclude: ^eff_word_net/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-pyyaml, types-requests, types-setuptools]
